# Generated by Django 4.2.6 on 2024-01-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(max_length=3)),
                ('pokemon_id', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=256)),
                ('style', models.CharField(max_length=10)),
                ('pokemon', models.CharField(max_length=15)),
                ('pokemon_set', models.CharField(max_length=15)),
                ('item', models.CharField(max_length=15)),
            ],
        ),
    ]
