# Generated by Django 4.2.6 on 2024-01-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory_aid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'managed': False},
        ),
    ]
