# Generated by Django 4.2.6 on 2024-01-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_aid', '0002_alter_pokemon_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_phrase', models.CharField(max_length=100)),
                ('style_phrase', models.CharField(max_length=100)),
                ('composing_sets', models.CharField(max_length=100)),
                ('composing_pokemon', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'factory_teams',
            },
        ),
        migrations.AlterModelTable(
            name='pokemon',
            table='factory_data',
        ),
    ]
